export const COUNTRIES = [
  { name: 'Ethiopia', code: '+251', iso: 'ET' },
  { name: 'United States', code: '+1', iso: 'US' },
  { name: 'Canada', code: '+1', iso: 'CA' },
  { name: 'United Kingdom', code: '+44', iso: 'GB' },
  { name: 'Australia', code: '+61', iso: 'AU' },
  { name: 'Germany', code: '+49', iso: 'DE' },
  { name: 'France', code: '+33', iso: 'FR' },
  { name: 'Italy', code: '+39', iso: 'IT' },
  { name: 'Spain', code: '+34', iso: 'ES' },
  { name: 'Netherlands', code: '+31', iso: 'NL' },
  { name: 'Sweden', code: '+46', iso: 'SE' },
  { name: 'Norway', code: '+47', iso: 'NO' },
  { name: 'Switzerland', code: '+41', iso: 'CH' },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE' },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA' },
  { name: 'Qatar', code: '+974', iso: 'QA' },
  { name: 'Kuwait', code: '+965', iso: 'KW' },
  { name: 'Oman', code: '+968', iso: 'OM' },
  { name: 'Bahrain', code: '+973', iso: 'BH' },
  { name: 'Israel', code: '+972', iso: 'IL' },
  { name: 'South Africa', code: '+27', iso: 'ZA' },
  { name: 'Kenya', code: '+254', iso: 'KE' },
  { name: 'Nigeria', code: '+234', iso: 'NG' },
  { name: 'Egypt', code: '+20', iso: 'EG' },
  { name: 'India', code: '+91', iso: 'IN' },
  { name: 'China', code: '+86', iso: 'CN' },
  { name: 'Japan', code: '+81', iso: 'JP' },
  { name: 'South Korea', code: '+82', iso: 'KR' },
  { name: 'Brazil', code: '+55', iso: 'BR' },
  { name: 'Mexico', code: '+52', iso: 'MX' },
  { name: 'Argentina', code: '+54', iso: 'AR' },
  { name: 'Russia', code: '+7', iso: 'RU' },
  { name: 'New Zealand', code: '+64', iso: 'NZ' },
  { name: 'Singapore', code: '+65', iso: 'SG' },
  { name: 'Malaysia', code: '+60', iso: 'MY' },
  { name: 'Thailand', code: '+66', iso: 'TH' },
  { name: 'Vietnam', code: '+84', iso: 'VN' },
  { name: 'Philippines', code: '+63', iso: 'PH' },
  { name: 'Indonesia', code: '+62', iso: 'ID' },
  { name: 'Turkey', code: '+90', iso: 'TR' },
  { name: 'Greece', code: '+30', iso: 'GR' },
  { name: 'Portugal', code: '+351', iso: 'PT' },
  { name: 'Ireland', code: '+353', iso: 'IE' },
  { name: 'Belgium', code: '+32', iso: 'BE' },
  { name: 'Austria', code: '+43', iso: 'AT' },
  { name: 'Denmark', code: '+45', iso: 'DK' },
  { name: 'Finland', code: '+358', iso: 'FI' },
  { name: 'Poland', code: '+48', iso: 'PL' }
];
