export interface Country {
  name: string;
  nameAm: string;
  code: string;
  iso: string;
}

export const COUNTRIES: Country[] = [
  { name: 'Ethiopia', nameAm: 'ኢትዮጵያ', code: '+251', iso: 'ET' },
  { name: 'United States', nameAm: 'አሜሪካ', code: '+1', iso: 'US' },
  { name: 'Canada', nameAm: 'ካናዳ', code: '+1', iso: 'CA' },
  { name: 'United Kingdom', nameAm: 'እንግሊዝ', code: '+44', iso: 'GB' },
  { name: 'Germany', nameAm: 'ጀርመን', code: '+49', iso: 'DE' },
  { name: 'United Arab Emirates', nameAm: 'የተባበሩት አረብ ኤምሬትስ', code: '+971', iso: 'AE' },
  { name: 'Saudi Arabia', nameAm: 'ሳውዲ አረቢያ', code: '+966', iso: 'SA' },
  { name: 'Israel', nameAm: 'እስራኤል', code: '+972', iso: 'IL' },
  { name: 'Norway', nameAm: 'ኖርዌይ', code: '+47', iso: 'NO' },
  { name: 'Sweden', nameAm: 'ስዊድን', code: '+46', iso: 'SE' },
  { name: 'Kenya', nameAm: 'ኬንያ', code: '+254', iso: 'KE' },
  { name: 'South Africa', nameAm: 'ደቡብ አፍሪካ', code: '+27', iso: 'ZA' },
  { name: 'Australia', nameAm: 'አውስትራሊያ', code: '+61', iso: 'AU' },
  { name: 'China', nameAm: 'ቻይና', code: '+86', iso: 'CN' },
  { name: 'Japan', nameAm: 'ጃፓን', code: '+81', iso: 'JP' },
  { name: 'France', nameAm: 'ፈረንሳይ', code: '+33', iso: 'FR' },
  { name: 'Italy', nameAm: 'ጣሊያን', code: '+39', iso: 'IT' },
  { name: 'Russia', nameAm: 'ሩሲያ', code: '+7', iso: 'RU' },
  { name: 'Turkey', nameAm: 'ቱርክ', code: '+90', iso: 'TR' },
  { name: 'Egypt', nameAm: 'ግብፅ', code: '+20', iso: 'EG' },
  { name: 'Sudan', nameAm: 'ሱዳን', code: '+249', iso: 'SD' },
  { name: 'South Sudan', nameAm: 'ደቡብ ሱዳን', code: '+211', iso: 'SS' },
  { name: 'Eritrea', nameAm: 'ኤርትራ', code: '+291', iso: 'ER' },
  { name: 'Djibouti', nameAm: 'ጅቡቲ', code: '+253', iso: 'DJ' },
  { name: 'Somalia', nameAm: 'ሶማሊያ', code: '+252', iso: 'SO' },
  { name: 'Uganda', nameAm: 'ኡጋንዳ', code: '+256', iso: 'UG' },
  { name: 'Tanzania', nameAm: 'ታንዛኒያ', code: '+255', iso: 'TZ' },
  { name: 'Switzerland', nameAm: 'ስዊዘርላንድ', code: '+41', iso: 'CH' },
  { name: 'Netherlands', nameAm: 'ኔዘርላንድስ', code: '+31', iso: 'NL' },
  { name: 'Belgium', nameAm: 'ቤልጂየም', code: '+32', iso: 'BE' },
  { name: 'Qatar', nameAm: 'ኳታር', code: '+974', iso: 'QA' },
  { name: 'Kuwait', nameAm: 'ኩዌት', code: '+965', iso: 'KW' },
  { name: 'Bahrain', nameAm: 'ባህሬን', code: '+973', iso: 'BH' },
  { name: 'Oman', nameAm: 'ኦማን', code: '+968', iso: 'OM' },
  { name: 'Lebanon', nameAm: 'ሊባኖስ', code: '+961', iso: 'LB' },
  { name: 'Jordan', nameAm: 'ዮርዳኖስ', code: '+962', iso: 'JO' },
  { name: 'India', nameAm: 'ህንድ', code: '+91', iso: 'IN' },
  { name: 'Pakistan', nameAm: 'ፓኪስታን', code: '+92', iso: 'PK' },
  { name: 'Yemen', nameAm: 'የመን', code: '+967', iso: 'YE' },
  { name: 'Iraq', nameAm: 'ኢራቅ', code: '+964', iso: 'IQ' },
  { name: 'Syria', nameAm: 'ሶሪያ', code: '+963', iso: 'SY' },
  { name: 'Iran', nameAm: 'ኢራን', code: '+98', iso: 'IR' },
  { name: 'Morocco', nameAm: 'ሞሮኮ', code: '+212', iso: 'MA' },
  { name: 'Algeria', nameAm: 'አልጄሪያ', code: '+213', iso: 'DZ' },
  { name: 'Libya', nameAm: 'ሊቢያ', code: '+218', iso: 'LY' },
  { name: 'Tunisia', nameAm: 'ቱኒዚያ', code: '+216', iso: 'TN' },
  { name: 'Nigeria', nameAm: 'ናይጄሪያ', code: '+234', iso: 'NG' },
  { name: 'Ghana', nameAm: 'ጋና', code: '+233', iso: 'GH' },
  { name: 'Cameroon', nameAm: 'ካሜሩን', code: '+237', iso: 'CM' },
  { name: 'Angola', nameAm: 'አንጎላ', code: '+244', iso: 'AO' },
  { name: 'Brazil', nameAm: 'ብራዚል', code: '+55', iso: 'BR' },
  { name: 'Argentina', nameAm: 'አርጀንቲና', code: '+54', iso: 'AR' },
  { name: 'Mexico', nameAm: 'ሜክሲኮ', code: '+52', iso: 'MX' },
  { name: 'Spain', nameAm: 'ስፔን', code: '+34', iso: 'ES' },
  { name: 'Portugal', nameAm: 'ፖርቱጋል', code: '+351', iso: 'PT' },
  { name: 'Greece', nameAm: 'ግሪክ', code: '+30', iso: 'GR' },
  { name: 'Ireland', nameAm: 'አየርላንድ', code: '+353', iso: 'IE' },
  { name: 'Austria', nameAm: 'ኦስትሪያ', code: '+43', iso: 'AT' },
  { name: 'Poland', nameAm: 'ፖላንድ', code: '+48', iso: 'PL' },
  { name: 'Ukraine', nameAm: 'ዩክሬን', code: '+380', iso: 'UA' },
  { name: 'New Zealand', nameAm: 'ኒው ዚላንድ', code: '+64', iso: 'NZ' },
  { name: 'Singapore', nameAm: 'ሲንጋፖር', code: '+65', iso: 'SG' },
  { name: 'Malaysia', nameAm: 'ማሌዥያ', code: '+60', iso: 'MY' },
  { name: 'Indonesia', nameAm: 'ኢንዶኔዥያ', code: '+62', iso: 'ID' },
  { name: 'South Korea', nameAm: 'ደቡብ ኮሪያ', code: '+82', iso: 'KR' },
  { name: 'Bahamas', nameAm: 'ባሃማስ', code: '+1-242', iso: 'BS' },
  { name: 'Finland', nameAm: 'ፊንላንድ', code: '+358', iso: 'FI' },
  { name: 'Denmark', nameAm: 'ዴንማርክ', code: '+45', iso: 'DK' }
];
