
const fs = require('fs');

const ar = {
  Index: { Hero: { tagline: 'الدفء التقليدي المطابقة الحديثة', title1: 'زيجات قوية', title2: 'عائلة لأجيال', subtitle: 'المنصة العالمية الأولى المخصصة لبناء منازل إثيوبية مستدامة من خلال المطابقة التي تركز على التراث والاستشارات المدعومة بالذكاء الاصطناعي.', cta1: 'إنشاء حساب', cta2: 'رؤيتنا', verify1: 'جواز سفر تم التحقق منه', verify2: 'هوية مضمونة', verify3: 'محرك أبو شاكر' },
  Vision: { tagline: 'تراثنا', title: 'الحفاظ على الأسرة في عالم رقمي', subtitle: 'في قلب رؤية بيتسب تكمن حكمة أبو شاكر. نمزج قرونًا من منطق التوفيق الإثيوبي مع التشفير السلوكي الحديث لإنشاء نقابات مقدسة تم التحقق منها.', cta: 'اكتشف رؤيتنا', stat: 'دقة المطابقة' },
  modal: { step1: 'الخطوة 1: الأمان والتسعير', where: 'أين تقع؟', currencyNote: 'نحن نستخدم موقعك لإظهار الأسعار بعملتك المحلية وحماية خصوصيتك.', localTitle: 'داخل إثيوبيا', localSub: 'المدفوعات بالبر', globalTitle: 'الشتات العالمي', globalSub: 'المدفوعات بالدولار' } },
  Nav: { home: 'الرئيسية', about: 'معلومات عنا', classes: 'فصول', signIn: 'تسجيل الدخول', signUp: 'انضم الآن', login: 'الدخول / إنشاء حساب', logout: 'تسجيل خروج', settings: 'إعدادات', dashboard: 'لوحة القيادة', chat: 'دردشة', community: 'مجتمع', workshops: 'ورش عمل', profile: 'الملف الشخصي' },
  Dashboard: { welcome: 'مرحباً بعودتك', subtitle: 'ابحث عن شريكك المثالي', premium: { active: 'بريميوم نشط', pending: 'قيد المراجعة', expired: 'انتهت الفترة التجريبية', unlock: 'افتح بريميوم' }, matching: { title: 'أعلى المطابقات', viewAll: 'عرض الكل', percent: 'تطابق' } },
  Footer: { tagline: 'بيتسب | المطابقة الإثيوبية', description: 'جمع العائلات معًا في جميع أنحاء العالم بالتقاليد والتكنولوجيا.', connect: 'تواصل', platform: 'منصة', legal: 'قانوني', vision: 'رؤيتنا', classes: 'فصول المطابقة', start: 'ابدأ المطابقة', terms: 'شروط الخدمة', privacy: 'سياسة الخصوصية', admin: 'بوابة الإدارة', copyright: '© 2026 بيتسب.', address: 'هرر، إثيوبيا', community: 'تغذية المجتمع' },
  Auth: { signIn: 'تسجيل الدخول', signUp: 'إنشاء حساب', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', password: 'كلمة المرور', forgot: 'هل نسيت كلمة المرور؟', noAccount: 'ليس لديك حساب؟', haveAccount: 'هل لديك حساب؟', phoneTab: 'هاتف', countryCode: 'كود البلد', processing: 'جاري المعالجة...' },
  community: { communityTitle: 'الاستشارة الأسرية والمجتمع', communitySubtitle: 'ناقش القيم التقليدية للزواج والمواضيع الثقافية', newPostPlaceholder: 'شارك أفكارك...', postButton: 'نشر في المجتمع', feedTitle: 'المناقشات الأخيرة', adminApprovalNote: 'تتم مراجعة المشاركات من قبل المشرفين', authorFormat: 'نشر بواسطة', pending: 'في انتظار الموافقة', languageToggle: 'تغيير اللغة', anonymousUser: 'مستخدم مجهول', noPosts: 'لا توجد مشاركات حتى الآن.', like: 'إعجاب', reply: 'رد', loginRequired: 'يرجى التسجيل للنشر' },
  About: { tagline: 'رؤيتنا', subtitle: 'بيتسب أكثر من مجرد منصة', missionTitle: 'المهمة', missionDesc: 'نحن نهدف إلى إزالة حواجز المسافة...', mission1: 'التحقق الإلزامي من الهوية', mission2: 'دمج منطق التوافق أبو شاكر', mission3: 'استشارات ما قبل الزواج', mission4: 'الاعتدال المجتمعي للخصوصية', principlesTag: 'المبادئ الأساسية', principlesTitle: 'التقاليد والثقة', value1Title: 'الأسرة أولا', value1Desc: 'كل ما نقوم به يركز على الأسرة', value2Title: 'الشرف الثقافي', value2Desc: 'نحن نحترم التقاليد', value3Title: 'الأمان المطلق', value3Desc: 'سياسة عدم التسامح', ctaTitle: 'كن جزءًا من الإرث', ctaButton: 'انضم إلى بيتسب اليوم', ourStory: 'قصتنا' },
  Resources: { learningHub: 'مركز التعلم', heroTitle: 'المعرفة من أجل {betterLife}', betterLife: 'حياة أفضل', searchPlaceholder: 'البحث في الموارد...', noMatch: 'لا توجد موارد مطابقة', noMatchSubtitle: 'حاول تعديل البحث', readCollection: 'قراءة المجموعة', deepLearn: 'هل تريد أن تتعلم {deeply}؟', deeply: 'بعمق أكبر؟', joinDesc: 'انضم إلى مجتمعنا للوصول الحصري' },
  Chatbot: { welcome: 'مرحبًا بك في بيتسب!', faq: { abushakir: 'يعتمد محرك التوافق لدينا على أبو شاكر', pricing: 'نحن نقدم أسعار متدرجة', verified: 'التحقق إلزامي', hello: 'مرحبا! أنا مساعدك', default: 'أنا متخصص في شرح نظامنا' }, placeholder: 'اسألني أي شيء...', status: 'مساعد عبر الإنترنت', btn: { abushakir: 'أبو شاكر', pricing: 'التسعير', verified: 'التحقق' } },
  Onboarding: { title: 'بوابة العائلة', personalDetails: 'تـفاصيل شخصية', personalSubtitle: 'لنبدأ بالأساسيات', demographics: 'التركيبة السكانية', career: 'الوظيفة وعلم النفس', reviewTitle: 'مراجعة الملف الشخصي', reviewSubtitle: 'يرجى تأكيد بياناتك', finishTitle: 'أنت جاهز!', finishSubtitle: 'جاري مراجعة ملفك', finishCTA: 'أدخل لوحة القيادة', fields: { email: 'البريد الإلكتروني', password: 'كلمة المرور', passwordHint: 'الحد الأدنى 6 أحرف', fullName: 'الاسم الكامل', fullNamePlaceholder: 'أبيبي', birthDate: 'تاريخ الميلاد', birthTime: 'وقت الميلاد', gender: 'الجنس', genderPlaceholder: 'اختر الجنس', location: 'الموقع', locationPlaceholder: 'اختر الموقع', religion: 'الدين', religionPlaceholder: 'اختر الدين', maritalStatus: 'الحالة الاجتماعية', maritalPlaceholder: 'اختر الحالة', jobTitle: 'المسمى الوظيفي', jobPlaceholder: 'مهندس', financeHabit: 'العادة المالية', financePlaceholder: 'اختر', familyValues: 'القيم العائلية', familyPlaceholder: 'اختر', conflictResolution: 'حل النزاعات', conflictPlaceholder: 'اختر', spouseRequirements: 'مواصفات الشريك', spousePlaceholder: 'وصف...', phone: 'رقم الهاتف', phoneTab: 'هاتف', starSign: 'برج النجم', unknown: 'غير معروف', abushakirBadge: 'محرك أبوشاكر', country: 'دولة' }, idVerification: { title: 'التحقق من الهوية', subtitle: 'الهوية الرسمية مطلوبة', uploadClick: 'انقر للتحميل {type}', uploadHint: 'PNG, JPG', uploaded: 'تم الرفع!' }, nav: { back: 'خلف', continue: 'يتابع', finish: 'إنهاء', processing: 'معالجة...' }, loading: 'جاري التحميل...', footerTagline: 'جمع العائلات الإثيوبية معًا' },
  Classes: { hero: { tagline: 'رحلة موجهة', title1: 'أكثر من المطابقة.', title2: 'حكمة العمر.', subtitle: 'انضم إلى ورش العمل', cta: 'سجل الان' }, list: { class1: { title: 'فهم أبو شاكر', desc: 'غوص عميق...', date: 'كل جمعة', badge: 'مجانا' }, class2: { title: 'القيم التقليدية', desc: 'الزواج الحديث...', date: 'كل خميس', badge: 'شائع' }, class3: { title: 'الرحلة المتحقق منها', desc: 'كيفية إعداد ملفك...', date: 'السبت', badge: 'دخول' } }, counseling: { tagline: 'دعم فردي', title1: 'خبراء.', title2: 'تحت تصرفك.', subtitle: 'مستشارونا يقدمون جلسات خاصة', stat1Value: '500+', stat1Label: 'مستشارون', stat2Value: '100%', stat2Label: 'سري', curriculumTitle: 'المنهج الدراسي', topics: { t1: 'التفاعل الثقافي', t2: 'حل النزاعات', t3: 'الإشراف المالي', t4: 'الأدوار التقليدية والحديثة' } }, footerMeta: 'تمكين الشتات', footerCTA: 'ابدأ ديسكفري' },
  TopHeader: { email: 'contact@beteseb.com', phone: '+49 123 456 789', suggestion: 'تفضل {lang}؟', switchBtn: 'بدل الآن' },
  Constants: {
    Religions: { Orthodox: 'أرثوذكسي', Protestant: 'بروتستانتي', Catholic: 'كاثوليكي', Muslim: 'مسلم', Other: 'أخرى' },
    Genders: { Male: 'ذكر', Female: 'أنثى' },
    Marital: { Single: 'أعزب', Divorced: 'مطلق', Widow: 'أرملة', Widower: 'أرمل' },
    Finance: { Spender: 'منفق', Saver: 'موفر', Balanced: 'متوازن', Frugal: 'مقتصد' },
    Values: { Traditional: 'تقليدي', Modern: 'حديث', Liberal: 'ليبرالي', 'Religious-Centric': 'ديني' },
    Conflict: { 'Direct Discussion': 'مناقشة مباشرة', 'Indirect / Subtle': 'غير مباشر', 'Silent Treatment': 'صمت', 'Mediation Required': 'يتطلب وساطة' },
    Locations: { 'Addis Ababa': 'أديس أبابا', 'Dire Dawa': 'دير داوا', 'Mekelle': 'ميكيلي', 'Adama': 'أداما', 'Bahir Dar': 'بحر دار', 'Gondar': 'جوندار', 'Hawassa': 'هواسا', 'Jimma': 'جيما', 'Jijiga': 'جيجيجا', 'Other (International)': 'دولي' }
  }
};

const am = {
  Index: { Hero: { tagline: 'ባህላዊ ሙቀት፣ ዘመናዊ ትውውቅ', title1: 'ጠንካራ ትዳር', title2: 'ለትውልድ የሚተርፍ ቤተሰብ', subtitle: 'የቤተሰብ እሴቶችን መሰረት በማድረግ እና በዘመናዊ ቴክኖሎጂ የታገዘ የኢትዮጵያ ቤተሰቦችን መገንቢያ መድረክ።', cta1: 'አካውንት ይፍጠሩ', cta2: 'ራእያችን', verify1: 'የተረጋገጠ', verify2: 'በማንነት ማረጋገጫ', verify3: 'አቡሻህር ሞተር' },
  Vision: { tagline: 'ቅርስ', title: 'ቤተሰብን በዲጂታል ዓለም', subtitle: 'በቤተሰብ ራዕይ ውስጥ የአቡሻህር ጥበብ አለ።', cta: 'ያግኙን', stat: 'የትክክለኛነት መጠን' },
  modal: { step1: 'ክፍያ', where: 'የት ነው ያሉት?', currencyNote: 'በምንዛሬ እናሳይዎታለን', localTitle: 'ኢትዮጵያ ውስጥ', localSub: 'በብር', globalTitle: 'በውጭ', globalSub: 'በዶላር' } },
  Nav: { home: 'መነሻ', about: 'ስለ እኛ', classes: 'ክፍሎች', signIn: 'ይግቡ', signUp: 'ይመዝገቡ', login: 'መግቢያ / መመዝገቢያ', logout: 'ይውጡ', settings: 'ቅንብሮች', dashboard: 'ማስተዳደሪያ', chat: 'ውይይት', community: 'ማህበረሰብ', workshops: 'ስልጠናዎች', profile: 'መገለጫ' },
  Dashboard: { welcome: 'እንኳን ደህና መጡ', subtitle: 'የህይወት አጋርዎን ያግኙ', premium: { active: 'ፕሪሚየም ነቅቷል', pending: 'ግምገማ ላይ', expired: 'የሙከራ ጊዜ አልቋል', unlock: 'ፕሪሚየም ይክፈቱ' }, matching: { title: 'ተዛማጅ', viewAll: 'ሁሉንም እይ', percent: 'ተዛማጅ' } },
  Footer: { tagline: 'ቤተሰብ | Beteseb', description: 'ቤተሰብን በባህል፣ በቴክኖሎጂ።', connect: 'ይገናኙ', platform: 'መድረክ', legal: 'ህጋዊ', vision: 'ራዕይ', classes: 'ክፍሎች', start: 'ይጀምሩ', terms: 'የአጠቃቀም ውል', privacy: 'ግላዊነት', admin: 'አስተዳዳሪ', copyright: '© 2026 ቤተሰብ.', address: 'ሀረር', community: 'ማህበረሰብ' },
  Auth: { signIn: 'ይግቡ', signUp: 'ይመዝገቡ', email: 'ኢሜል', phone: 'ስልክ ቁጥር', password: 'የይለፍ ቃል', forgot: 'የይለፍ ቃል ረሱ?', noAccount: 'አካውንት የለዎትም?', haveAccount: 'አካውንት አለዎት?', phoneTab: 'ስልክ', countryCode: 'ሀገር', processing: 'እየተከናወነ ነው...' },
  community: { communityTitle: 'የቤተሰብ ምክክር', communitySubtitle: 'ስለ ባህል እሴቶች ይወያዩ', newPostPlaceholder: 'ሀሳብዎን ያካፍሉ...', postButton: 'ለማህበረሰቡ ያጋሩ', feedTitle: 'ውይይቶች', adminApprovalNote: 'በአስተዳዳሪ ይገመገማል', authorFormat: 'በ', pending: 'ግምገማ ላይ', languageToggle: 'ቋንቋ ቀይር', anonymousUser: 'ያልታወቀ ተጠቃሚ', noPosts: 'ምንም የለም', like: 'ወድጄዋለሁ', reply: 'መልስ', loginRequired: 'ለመሳተፍ ይግቡ' },
  About: { tagline: 'ለኢትዮጵያዊ ልብ', subtitle: 'ከማዛመጃ በላይ', missionTitle: 'ተልዕኮው', missionDesc: 'ርቀትን ማስወገድ', mission1: 'ማንነት ማረጋገጫ ግዴታ ነው', mission2: 'አቡሻህር', mission3: 'የቅድመ ጋብቻ ምክር', mission4: 'የማህበረሰብ ቁጥጥር', principlesTag: 'መርሆዎች', principlesTitle: 'ባህል. እምነት', value1Title: 'ቤተሰብ ይቀድማል', value1Desc: '...', value2Title: 'ባህላዊ ክብር', value2Desc: '...', value3Title: 'ደህንነት', value3Desc: '...', ctaTitle: 'የቅርሱ አካል ይሁኑ', ctaButton: 'ቤተሰብን ይቀላቀሉ', ourStory: 'ታሪካችን' },
  Resources: { learningHub: 'ማዕከል', heroTitle: 'እውቀት ለ {betterLife}', betterLife: 'ተሻለ ህይወት', searchPlaceholder: 'ይፈልጉ...', noMatch: 'አልተገኘም', noMatchSubtitle: 'እንደገና ይሞክሩ', readCollection: 'ያንብቡ', deepLearn: 'መማር ይፈልጋሉ {deeply}?', deeply: 'በጥልቀት', joinDesc: 'ማህበረሰባችንን ይቀላቀሉ' },
  Chatbot: { welcome: 'ወደ ቤተሰብ እንኳን ደህና መጡ', faq: { abushakir: 'አቡሻህር...', pricing: 'ክፍያ...', verified: 'ማረጋገጫ...', hello: 'ሰላም...', default: 'እኔ ረዳት ነኝ' }, placeholder: 'የፈለጉትን ይጠይቁ...', status: 'ረዳት', btn: { abushakir: 'አቡሻህር', pricing: 'ክፍያ', verified: 'ማረጋገጫ' } },
  Onboarding: { title: 'የቤተሰብ መግቢያ', personalDetails: 'የግል መረጃ', personalSubtitle: 'መሰረታዊ ነገሮችን እንጀምር', demographics: 'ስነ-ህዝባዊ', career: 'ሙያ', reviewTitle: 'መገለጫውን ይገምግሙ', reviewSubtitle: 'ያረጋግጡ', finishTitle: 'ተጠናቋል!', finishSubtitle: 'መገለጫ እየተገመገመ ነው', finishCTA: 'ወደ ማስተዳደሪያ ይግቡ', fields: { email: 'ኢሜል', password: 'የይለፍ ቃል', passwordHint: '6 ቁምፊዎች', fullName: 'ሙሉ ስም', fullNamePlaceholder: 'አበበ', birthDate: 'የልደት ቀን', birthTime: 'ሰዓት', gender: 'ጾታ', genderPlaceholder: 'ይምረጡ', location: 'ቦታ', locationPlaceholder: 'ይምረጡ', religion: 'ሃይማኖት', religionPlaceholder: 'ይምረጡ', maritalStatus: 'የጋብቻ ሁኔታ', maritalPlaceholder: 'ይምረጡ', jobTitle: 'የሥራ መደብ', jobPlaceholder: 'ምሳሌ፡ መሃንዲስ', financeHabit: 'የገንዘብ አያያዝ', financePlaceholder: 'ይምረጡ', familyValues: 'የቤተሰብ እሴት', familyPlaceholder: 'ይምረጡ', conflictResolution: 'ግጭት አፈታት', conflictPlaceholder: 'ይምረጡ', spouseRequirements: 'መስፈርት', spousePlaceholder: 'ይግለጹ', phone: 'ስልክ ቁጥር', phoneTab: 'ስልክ', starSign: 'ኮከብ', unknown: 'ያልታወቀ', abushakirBadge: 'አቡሻህር', country: 'ሀገር' }, idVerification: { title: 'ማንነትን ማረጋገጥ', subtitle: 'መታወቂያ ያስፈልጋል', uploadClick: 'መታወቂያ ይጫኑ {type}', uploadHint: 'PNG, JPG', uploaded: 'ተጭኗል!' }, nav: { back: 'ተመለስ', continue: 'ቀጥል', finish: 'ጨርስ', processing: 'እየተከናወነ ነው...' }, loading: 'እየተጫነ ነው...', footerTagline: 'የኢትዮጵያ ቤተሰቦችን በመላው ዓለም ማገናኘት' },
  Classes: { hero: { tagline: 'ማዛመድ', title1: 'ከማዛመድ በላይ', title2: 'ጥበብ', subtitle: 'ስልጠና ይመዝገቡ', cta: 'ይመዝገቡ' }, list: { class1: { title: 'አቡሻህር', desc: '...', date: 'ማክሰኞ', badge: 'ነፃ' }, class2: { title: 'ባህል', desc: '...', date: 'ሐሙስ', badge: 'ተፈላጊ' }, class3: { title: 'ማረጋገጫ', desc: '...', date: 'ቅዳሜ', badge: 'አዲስ' } }, counseling: { tagline: 'ድጋፍ', title1: 'ባለሙያዎች', title2: 'ለእርስዎ', subtitle: 'የግል ምክክር', stat1Value: '500+', stat1Label: 'አማካሪዎች', stat2Value: '100%', stat2Label: 'ሚስጥራዊ', curriculumTitle: 'ትምህርት', topics: { t1: 'ግንኙነት', t2: 'ግጭት አፈታት', t3: 'ፋይናንስ', t4: 'ባህላዊ ሚናዎች' } }, footerMeta: 'ዲያስፖራ', footerCTA: 'ይጀምሩ' },
  TopHeader: { email: 'contact@beteseb.com', phone: '+49 123 456 789', suggestion: 'ምርጫዎ {lang} ነው?', switchBtn: 'ቀይር' },
  Constants: {
    Religions: { Orthodox: 'ኦርቶዶክስ', Protestant: 'ፕሮቴስታንት', Catholic: 'ካቶሊክ', Muslim: 'ሙስሊም', Other: 'ሌላ' },
    Genders: { Male: 'ወንድ', Female: 'ሴት' },
    Marital: { Single: 'ያላገባ/ች', Divorced: 'የተፋታ/ች', Widow: 'አርማ', Widower: 'አርማ' },
    Finance: { Spender: 'አውጪ', Saver: 'ቆጣቢ', Balanced: 'መካከለኛ', Frugal: 'ቁጥብ' },
    Values: { Traditional: 'ባህላዊ', Modern: 'ዘመናዊ', Liberal: 'ሊበራል', 'Religious-Centric': 'ሃይማኖታዊ' },
    Conflict: { 'Direct Discussion': 'መወያየት', 'Indirect / Subtle': 'በተዘዋዋሪ', 'Silent Treatment': 'ዝምታ', 'Mediation Required': 'ሽምግልና' },
    Locations: { 'Addis Ababa': 'አዲስ አበባ', 'Dire Dawa': 'ድሬ ዳዋ', 'Mekelle': 'መቀሌ', 'Adama': 'አዳማ', 'Bahir Dar': 'ባህር ዳር', 'Gondar': 'ጎንደር', 'Hawassa': 'ሀዋሳ', 'Jimma': 'ጅማ', 'Jijiga': 'ጅጅጋ', 'Other (International)': 'ከሀገር ውጭ' }
  }
};

const om = JSON.parse(JSON.stringify(am)); // Just mirror for placeholder for om.json to avoid crash

fs.writeFileSync('messages/ar.json', JSON.stringify(ar, null, 2));
fs.writeFileSync('messages/am.json', JSON.stringify(am, null, 2));
fs.writeFileSync('messages/om.json', JSON.stringify(om, null, 2));
