const fs = require('fs');
const path = require('path');

// Add all Subscription page keys to en.json and all locales
const subKeys = {
  en: {
    Subscription: {
      hub: "Beteseb Diamond & VIP Hub",
      welcomeVip: "Welcome to VIP Status",
      welcomeDiamond: "Welcome to Diamond Status",
      descVip: "Exquisite privacy controls, complete incognito features, and golden crown status for elite matchmaking.",
      descDiamond: "Unlock unlimited matches, contact profiles directly, access expert classes, and find your lifetime partner today.",
      diamondPlans: "Diamond Plans",
      vipPlans: "VIP Plans",
      keyFeatures: "Key Features & Benefits",
      feat1Title: "Unlimited Matching Feed",
      feat1Desc: "Bypass the trust tier daily card limits and explore profiles without restrictions.",
      feat2Title: "Direct Private Chat",
      feat2Desc: "Start chatting with matches instantly without wait limits.",
      feat3Title: "View Full Details & Bios",
      feat3Desc: "Reveal blurred profile traits, descriptions, and user bios.",
      feat4Title: "Priority Customer Care",
      feat4Desc: "Your support requests and verification status updates are prioritized.",
      feat5Title: "Golden Crown Status",
      feat5Desc: "Stand out with an elegant Crown Badge on your avatar and details page.",
      feat6Title: "Ghost Mode & Privacy",
      feat6Desc: "Completely blur your avatar image and hide your full name.",
      feat7Title: "Incognito Online Controls",
      feat7Desc: "Hide your online active indicators, typing state, and read receipts.",
      feat8Title: "All Diamond Benefits Included",
      feat8Desc: "Enjoy complete Diamond access in addition to your exclusive VIP features.",
      selectedCategory: "Selected Category",
      totalAmount: "Total Amount Due",
      discountApplied: "Discount Applied",
      completeUpgrade: "Complete Upgrade",
      secureGateway: "Secure gateway • Activated instantly",
      bestOffer: "Best Offer",
      submitClaimBtn: "Paid but service not activated? Submit a claim",
      claimTitle: "Submit Payment Claim",
      claimTxLabel: "Transaction ID / Reference",
      claimTypeLabel: "Payment Type",
      claimExplainLabel: "Explanation",
      claimExplainPlaceholder: "Describe what happened (amount paid, method, etc.)...",
      claimSubmit: "Submit Claim",
      paymentFailed: "Payment Initialization Failed",
      claimSuccess: "Claim Submitted",
      claimSuccessMsg: "Your payment claim has been submitted successfully under ticket {ticket}. Admins will verify it shortly.",
      typeVip: "VIP Upgrade",
      typeDiamond: "Diamond Upgrade",
      typeCoins: "Coins Package (100-10000 Coins)",
      // Plan names (period labels)
      plan1m: "1 Month",
      plan3m: "3 Months (15% Off)",
      plan6m: "6 Months (28% Off)",
      plan12m: "1 Year (44% Off)",
      planLifetime: "Lifetime Access",
      plan1mVip: "1 Month VIP",
      plan3mVip: "3 Months VIP (15% Off)",
      plan6mVip: "6 Months VIP (28% Off)",
      plan12mVip: "1 Year VIP (44% Off)",
      planLifetimeVip: "Lifetime VIP",
      periodMonthly: "monthly",
      periodQuarterly: "quarterly",
      periodSemiAnnual: "semi-annually",
      periodYearly: "yearly",
      periodLifetime: "lifetime"
    },
    Community: {
      following: "Following",
      follow: "Follow",
      deletePost: "Delete Post",
      deepLinkShare: "Share"
    },
    Workshops: {
      topicLabel: "Topic",
      timeSlotLabel: "Time Slot",
      topicPreMarriage: "Pre-Marriage Guidance",
      topicFinance: "Family Finance Planning",
      topicConflict: "Conflict Resolution",
      topicGeneral: "General Consultation"
    },
    Dashboard: {
      profile: {
        completion: "Profile Completion"
      }
    }
  },
  am: {
    Subscription: {
      hub: "ቤተሰብ ዳይመንድ እና ቪአይፒ",
      welcomeVip: "እንኳን ወደ ቪአይፒ አገልግሎት በደህና መጡ",
      welcomeDiamond: "እንኳን ወደ ዳይመንድ አገልግሎት በደህና መጡ",
      descVip: "የእርስዎን ግላዊነት ሙሉ በሙሉ የሚቆጣጠሩበት፣ ከፍተኛ ጥበቃ የሚደረግለት እና ልዩ የሆኑ ፊቸሮችን የሚያገኙበት የቪአይፒ ክለብ።",
      descDiamond: "ያልተገደበ የጽሑፍ ውይይት፣ ሙሉ የመገለጫ መረጃዎች እና ምርጥ አማራጮችን በማግኘት የትዳር አጋርዎን በፍጥነት ያግኙ።",
      diamondPlans: "የዳይመንድ አባልነት",
      vipPlans: "ቪአይፒ አባልነት",
      keyFeatures: "የሚያገኟቸው ዋና ጥቅሞች",
      feat1Title: "ያልተገደበ የትዳር አጋር ማግኘት",
      feat1Desc: "የየቀኑን ገደብ በማለፍ ሁሉንም መገለጫዎች ይጎብኙ።",
      feat2Title: "የቀጥታ ውይይት",
      feat2Desc: "ለሚፈልጉት ሰው ወዲያውኑ የጽሑፍ ውይይት ይጀምሩ።",
      feat3Title: "የሰዎች ሙሉ ዝርዝር መረጃ",
      feat3Desc: "የሰዎችን ባዮ፣ ምርጫዎች እና ዝርዝር መረጃዎች ይክፈቱ።",
      feat4Title: "ቅድሚያ የሚሰጠው የድጋፍ አገልግሎት",
      feat4Desc: "ማንኛውም ችግር ሲያጋጥምዎት ቅድሚያ ድጋፍ ያገኛሉ።",
      feat5Title: "የወርቅ አክሊል ባጅ (Crown Badge)",
      feat5Desc: "በሁሉም ቦታዎች ላይ የወርቅ አክሊል ባጅ መገለጫዎ ላይ ይደረጋል።",
      feat6Title: "የመደበቂያ ሁነታ (Ghost Mode)",
      feat6Desc: "ፎቶዎን መደበቅ እና ስምዎን ማደብዘዝ ይችላሉ።",
      feat7Title: "የመስመር ላይ መገኘትን መደበቅ",
      feat7Desc: "online መሆንዎን፣ የተነበበ ምልክትን መደበቅ ይችላሉ።",
      feat8Title: "ሁሉንም የዳይመንድ አገልግሎት ያካትታል",
      feat8Desc: "ያልተገደበ መገለጫ፣ የቀጥታ ቻት እና ሌሎችንም ያካትታል።",
      selectedCategory: "የተመረጠው አገልግሎት",
      totalAmount: "ጠቅላላ ክፍያ",
      discountApplied: "ቅናሽ ተደርጓል",
      completeUpgrade: "ክፍያን ፈጽም",
      secureGateway: "አስተማማኝ ክፍያ • ወዲያውኑ ገባሪ ይሆናል",
      bestOffer: "ተመራጭ",
      submitClaimBtn: "ክፍያ ፈጽመው አልሰራልዎትም? ቅሬታ ያቅርቡ",
      claimTitle: "የክፍያ ቅሬታ ማቅረቢያ",
      claimTxLabel: "የትራንዛክሽን ቁጥር (Transaction ID / Reference)",
      claimTypeLabel: "የክፍያ ዓይነት",
      claimExplainLabel: "ማብራሪያ",
      claimExplainPlaceholder: "የተፈጠረውን ችግር እዚህ ያብራሩ...",
      claimSubmit: "ቅሬታውን አቅርብ",
      paymentFailed: "የክፍያ ችግር ተፈጥሯል",
      claimSuccess: "ቅሬታው ቀርቧል",
      claimSuccessMsg: "የክፍያ ቅሬታዎ በትኬት ቁጥር {ticket} በተሳካ ሁኔታ ተመዝግቧል። አድሚኑ መርምሮ ወዲያውኑ አገልግሎቱን ያነቃቃል።",
      typeVip: "VIP አሳድግ",
      typeDiamond: "ዳይመንድ አሳድግ",
      typeCoins: "የኮይን ጥቅል (100-10000 ኮይን)",
      plan1m: "1 ወር",
      plan3m: "3 ወር (15% ቅናሽ)",
      plan6m: "6 ወር (28% ቅናሽ)",
      plan12m: "1 ዓመት (44% ቅናሽ)",
      planLifetime: "የዕድሜ ልክ",
      plan1mVip: "1 ወር VIP",
      plan3mVip: "3 ወር VIP (15% ቅናሽ)",
      plan6mVip: "6 ወር VIP (28% ቅናሽ)",
      plan12mVip: "1 ዓመት VIP (44% ቅናሽ)",
      planLifetimeVip: "የዕድሜ ልክ VIP",
      periodMonthly: "በወር",
      periodQuarterly: "በ3 ወር",
      periodSemiAnnual: "በ6 ወር",
      periodYearly: "በዓመት",
      periodLifetime: "ቋሚ"
    },
    Community: {
      following: "ተከታዮ ነዎት",
      follow: "ተከተሉ",
      deletePost: "ልጥፍ ሰርዝ",
      deepLinkShare: "አጋሩ"
    },
    Workshops: {
      topicLabel: "ርዕስ",
      timeSlotLabel: "የጊዜ ቦታ",
      topicPreMarriage: "ቅድመ-ጋብቻ መመሪያ",
      topicFinance: "የቤተሰብ የፋይናንስ እቅድ",
      topicConflict: "ግጭት አፈታት",
      topicGeneral: "አጠቃላይ ምክክር"
    },
    Dashboard: {
      profile: {
        completion: "የፕሮፋይል ሙሉነት"
      }
    }
  },
  om: {
    Subscription: {
      hub: "Beteseb Daayimandii fi VIP",
      welcomeVip: "Baga Tajaajila VIPtti Dhuftan",
      welcomeDiamond: "Baga Tajaajila Daayimandii Dhuftan",
      descVip: "Dhuunfummaa keessan guutumaan bulchuuf, eegumsa olaanaa argachuuf fi tajaajila VIP addaa argachuuf giddugala.",
      descDiamond: "Hiriyaa hin-daangaofame argachuu, piroofaayilii kallattiin quunnamuu, mana barumsaa ogeeyyii fayyadamuu fi hiriyaa jireenyaa keessan hardhuma argadhaa.",
      diamondPlans: "Karoora Daayimandii",
      vipPlans: "Karoora VIP",
      keyFeatures: "Tajaajilaalee fi Faayidaalee Ijoo",
      feat1Title: "Hiriyaa Daangoo Malee Argachuu",
      feat1Desc: "Daangoo guyyaa dabarsuun piroofaayilii hunda daawwadhaa.",
      feat2Title: "Haasaa Kallattii",
      feat2Desc: "Hiriyaalee wajjin yeroo illee haasaa jalqabaa.",
      feat3Title: "Odeeffannoo Guutuu Argachuu",
      feat3Desc: "Odeeffannoo, ibsa fi piroofaayilii guutuu banaa.",
      feat4Title: "Deeggarsa Dursa Kenname",
      feat4Desc: "Gaaffiin deeggarsa keessan dursa ilaalama.",
      feat5Title: "Baajii Achiichaa Warqee",
      feat5Desc: "Baajii warqee piroofaayilii keessan irratti argama.",
      feat6Title: "Haaloo Dhokannoo",
      feat6Desc: "Fakkii keessan dhoksuuf fi maqaa keessan dhofsisuu dandeessu.",
      feat7Title: "Mul'ina Interneetii Dhoksuuf",
      feat7Desc: "Haala online ta'uu fi mallattoo dubbifamuu dhokachuu dandeessu.",
      feat8Title: "Tajaajila Daayimandii Hunda Dabalata",
      feat8Desc: "Daayimandii guutuu fi tajaajila VIP addaa ni argatu.",
      selectedCategory: "Tajaajila Filatame",
      totalAmount: "Kafaltii Waliigalaa",
      discountApplied: "Hir'anni Raawwatameera",
      completeUpgrade: "Kafaltii Xumuri",
      secureGateway: "Karaa nageenyaa • Yeroo xumurtan banama",
      bestOffer: "Filatamaa",
      submitClaimBtn: "Kafaltii raawwataniituu hinseenamne? Gaaffii dhiyeessaa",
      claimTitle: "Gaaffii Kafaltii Dhiyeessuu",
      claimTxLabel: "Lakk. Daddabarsa (Transaction ID)",
      claimTypeLabel: "Gosa Kafaltii",
      claimExplainLabel: "Ibsa",
      claimExplainPlaceholder: "Rakkoo uumame asitti ibsaa...",
      claimSubmit: "Gaaffii Dhiyeessi",
      paymentFailed: "Rakkoo Kafaltii",
      claimSuccess: "Gaaffiin Dhiyaateera",
      claimSuccessMsg: "Gaaffiin kafaltii keessan tikeeta lakk {ticket} jalatti galmeera. Adminiistireetaroonni dhihottuma mirkaneesu.",
      typeVip: "VIP Haaromsuu",
      typeDiamond: "Daayimandii Haaromsuu",
      typeCoins: "Kooyina Saanduqa (100-10000)",
      plan1m: "Ji'a 1",
      plan3m: "Ji'oota 3 (15% hir'ina)",
      plan6m: "Ji'oota 6 (28% hir'ina)",
      plan12m: "Waggaa 1 (44% hir'ina)",
      planLifetime: "Jireenyaa guutuu",
      plan1mVip: "Ji'a 1 VIP",
      plan3mVip: "Ji'oota 3 VIP (15% hir'ina)",
      plan6mVip: "Ji'oota 6 VIP (28% hir'ina)",
      plan12mVip: "Waggaa 1 VIP (44% hir'ina)",
      planLifetimeVip: "Jireenyaa guutuu VIP",
      periodMonthly: "ji'aan",
      periodQuarterly: "Ji'a 3n",
      periodSemiAnnual: "Ji'a 6n",
      periodYearly: "waggaan",
      periodLifetime: "yeroo hundaa"
    },
    Community: {
      following: "Hordofaa",
      follow: "Hordofuu",
      deletePost: "Maxxansaa Haquu",
      deepLinkShare: "Qooduu"
    },
    Workshops: {
      topicLabel: "Mata-Duree",
      timeSlotLabel: "Yeroo Kenname",
      topicPreMarriage: "Gorsa Dursaa Gaa'elaa",
      topicFinance: "Bulchiinsa Maallaqaa Maatii",
      topicConflict: "Furmaata Waldhabdee",
      topicGeneral: "Gorsa Waliigalaa"
    },
    Dashboard: {
      profile: {
        completion: "Guutummaa Piroofaayilii"
      }
    }
  },
  ti: {
    Subscription: {
      hub: "ቤተሰብ ዳይሞንድ ን VIP",
      welcomeVip: "ናብ VIP ኣገልግሎት ብደሓን ምጽኡ",
      welcomeDiamond: "ናብ ዳይሞንድ ኣገልግሎት ብደሓን ምጽኡ",
      descVip: "ምስጢራውነትካ ብዝሙሉ ንምቁጽጻር፣ ልዑል ዕቃቤ ንምርካብን ፍሉይ ናይ VIP ምኽርን ዝህብ ናይ ኣባልነት ክለብ።",
      descDiamond: "ዘይተወሰነ ምድላይ ናይ ሓጋዚ፣ ቀጥታ ምርኻብ፣ ናይ ፍሉያት ኮርሳት ምኽታልን ናይ ህይወት ሓጋዚ ዛሓጺሩ ምርካብን።",
      diamondPlans: "ናይ ዳይሞንድ ኣባልነት",
      vipPlans: "ናይ VIP ኣባልነት",
      keyFeatures: "ዋና ኣገልግሎታትን ጥቕምታትን",
      feat1Title: "ዘይተወሰነ ምርካብ ሓጋዚ",
      feat1Desc: "ናይ ዕለታዊ ደረት ብምሕላፍ ኩሎም ፕሮፋይላት ዳህስሱ።",
      feat2Title: "ቀጥታ ምዝርራብ",
      feat2Desc: "ምስ ዝደለኻዮ ሰብ ወዲኡ ዝጀምር ናይ ጽሑፍ ወዝ ጀምር።",
      feat3Title: "ምሉእ ዝርዝር ምርኣይ",
      feat3Desc: "ናይ ሰባት ባዮ፣ ምርጫ፣ ዝርዝርን ኩሎምን ክፈት።",
      feat4Title: "ቅዳሜ-ቀዳምነት ደገፍ",
      feat4Desc: "ናይ ደገፍ ሕቶኻ ቅዳሜ ቀዳምነት ይሕዝ።",
      feat5Title: "ናይ ወርቂ ዘውዲ ባጅ",
      feat5Desc: "ኣብ ኩሎም ቦታ ናይ ወርቂ ዘውዲ ባጅ ኣብ ፕሮፋይልካ ይረአ።",
      feat6Title: "ምሽዋር / Ghost Mode",
      feat6Desc: "ናይ ሸነኽ ስእሊ ምሽዋርን ምሉእ ስምካ ምሕባእን ትኽእል።",
      feat7Title: "ናይ ኦንላይን ምርኣይ ምሕባእ",
      feat7Desc: "ኦንላይን ምዃንካ፣ ናይ ምንባብ ምልክት፣ ምሕባእ ትኽእል።",
      feat8Title: "ኩሎም ናይ ዳይሞንድ ኣገልግሎት ዘካትት",
      feat8Desc: "ምሉእ ዳይሞንድን ፍሉይ VIPን ኣገልግሎት ኣካቲቱ ይሓዝ።",
      selectedCategory: "ዝተመርጸ ኣገልግሎት",
      totalAmount: "ጠቅላላ ክፍሊት",
      discountApplied: "ቅናሽ ተተግቢሩ",
      completeUpgrade: "ክፍሊት ፈጽም",
      secureGateway: "ውሑስ ክፍሊት • ብቐጥታ ይነቃቕ",
      bestOffer: "እቲ ዝሓሸ",
      submitClaimBtn: "ክፍሊት ፈጺምካ ኣይሰርሐን? ቅሬታ ኣቕርብ",
      claimTitle: "ናይ ክፍሊት ቅሬታ ምቕራብ",
      claimTxLabel: "ቁጽሪ ዕድዌ (Transaction ID)",
      claimTypeLabel: "ዓይነት ክፍሊት",
      claimExplainLabel: "ብርሃን",
      claimExplainPlaceholder: "ዝኾነ ዝተፈጥረ ጸገም ኣብዚ ብርሃን ሃብ...",
      claimSubmit: "ቅሬታ ኣቕርብ",
      paymentFailed: "ጸገም ናይ ክፍሊት",
      claimSuccess: "ቅሬታ ቀሪቡ",
      claimSuccessMsg: "ናይ ክፍሊት ቅሬታኻ ብቲኬት ቁጽሪ {ticket} ኣምዝጊቡ ኣሎ። ኣድሚናት ብቀልጡፍ ሰርሖ ክፈቱሉ እዮም።",
      typeVip: "VIP ኣማህይሽ",
      typeDiamond: "ዳይሞንድ ኣማህይሽ",
      typeCoins: "ናይ ኮይን ጥሒሎ (100-10000)",
      plan1m: "1 ወርሒ",
      plan3m: "3 ወርሒ (15% ቅናሽ)",
      plan6m: "6 ወርሒ (28% ቅናሽ)",
      plan12m: "1 ዓመት (44% ቅናሽ)",
      planLifetime: "ናይ ዕድሜ",
      plan1mVip: "1 ወርሒ VIP",
      plan3mVip: "3 ወርሒ VIP (15% ቅናሽ)",
      plan6mVip: "6 ወርሒ VIP (28% ቅናሽ)",
      plan12mVip: "1 ዓመት VIP (44% ቅናሽ)",
      planLifetimeVip: "ናይ ዕድሜ VIP",
      periodMonthly: "ወርሓዊ",
      periodQuarterly: "3 ወርሒ",
      periodSemiAnnual: "6 ወርሒ",
      periodYearly: "ዓመታዊ",
      periodLifetime: "ንሓዋሩ"
    },
    Community: {
      following: "ትሰዕቦ ኣሎኻ",
      follow: "ስዓብ",
      deletePost: "ምሕዛዝ ፖስት",
      deepLinkShare: "ኣካፍሉ"
    },
    Workshops: {
      topicLabel: "ኣርዕስቲ",
      timeSlotLabel: "ናይ ግዜ ቦታ",
      topicPreMarriage: "ናይ ቅድሚ መርዓ ምኽሪ",
      topicFinance: "ናይ ቤተሰብ ፋይናንስ ምምሕዳር",
      topicConflict: "ፍታሕ ናይ ምፍጣሕ",
      topicGeneral: "ሓፈሻዊ ምኽሪ"
    },
    Dashboard: {
      profile: {
        completion: "ምሉእነት ፕሮፋይል"
      }
    }
  },
  so: {
    Subscription: {
      hub: "Beteseb Diamond iyo VIP",
      welcomeVip: "Ku Soo Dhowow Xaaladda VIP",
      welcomeDiamond: "Ku Soo Dhowow Xaaladda Diamond",
      descVip: "Xukun khaaskaaga si buuxda, astaamaha sirta ah oo dhammaystiran, iyo kiisaska goobta VIP.",
      descDiamond: "Fur is-fitiinnada aan xad lahayn, la xiriir profiles si toos ah, gal fasallada xirfadlayaasha, oo helo lammaanahaaga nolol ahaan maanta.",
      diamondPlans: "Qorshayaasha Diamond",
      vipPlans: "Qorshayaasha VIP",
      keyFeatures: "Astaamaha iyo Faa'iidooyinka Muhiimka ah",
      feat1Title: "Feejignaan Aan Xad Lahayn",
      feat1Desc: "Ka gudub xaddiga kartada maalinlaha ah oo baadh profiles xoriyadda leh.",
      feat2Title: "Wada-hadal Toos ah",
      feat2Desc: "Bilow wada-hadalka is-fitiinnada si degdeg ah adoon sugitaan lahayn.",
      feat3Title: "Arag Faahfaahinta & Siiradaha Buuxa",
      feat3Desc: "Fur astaamaha profile-ka ee xiran, faahfaahinta, iyo siirada isticmaalaha.",
      feat4Title: "Xaaladda Taageerada Mudnaanta",
      feat4Desc: "Codsigaaga taageerada iyo cusbooneysiinta xaaladda xaqiijinta waxaa la siinayaa mudnaan.",
      feat5Title: "Xaaladda Taajka Dahab",
      feat5Desc: "Kaga muuqo Astaanta Taajka Qurxoon ee sawirkaaga iyo bogga faahfaahinta.",
      feat6Title: "Qaabka Sirta & Ghost Mode",
      feat6Desc: "Buuxda dhig sawirkaaga oo qari magacaaga oo buuxa.",
      feat7Title: "Kontaroolka Khadka ee Sireed",
      feat7Desc: "Qari tilmaamayaashaada firfircoon ee khadka, xaaladda qoraallada, iyo diiwaanada akhrinta.",
      feat8Title: "Dhammaan Faa'iidooyinka Diamond Waxa Ku Jira",
      feat8Desc: "Ku raaxayso helitaanka Diamond oo buuxa iyo astaamahaaga gaarka ah ee VIP.",
      selectedCategory: "Qaybta la Doortay",
      totalAmount: "Wadarta Lacagta La Bixinayo",
      discountApplied: "Dhimista La Dabaqay",
      completeUpgrade: "Dhamaystir Hormarinta",
      secureGateway: "Albaabka amaan • Waxaa la firfircoonayaa si degdeg ah",
      bestOffer: "Heshiiska Ugu Wanaagsan",
      submitClaimBtn: "Waxaad bixisay laakiin adeeggu ma shaqeyn? Soo gudbi dacwad",
      claimTitle: "Soo Gudbi Dacwadda Lacag Bixinta",
      claimTxLabel: "Lambarka Macaamilka (Transaction ID)",
      claimTypeLabel: "Nooca Lacag Bixinta",
      claimExplainLabel: "Sharaxaad",
      claimExplainPlaceholder: "Sharax waxa dhacay (lacagta la bixiyay, hab, iwm)...",
      claimSubmit: "Gudbi Dacwadda",
      paymentFailed: "Dhibaato Lacag Bixinta",
      claimSuccess: "Dacwadda Waa La Gudbiyay",
      claimSuccessMsg: "Dacwaddaada lacag bixinta waxaa lagu diiwaangeliyay tigidhka {ticket}. Maamulayaasha ayaa xaqiijin doona si dhakhso ah.",
      typeVip: "Kor u qaad VIP",
      typeDiamond: "Kor u qaad Diamond",
      typeCoins: "Xidmo Qadaadac (100-10000)",
      plan1m: "1 Bil",
      plan3m: "3 Bilood (15% Dhimis)",
      plan6m: "6 Bilood (28% Dhimis)",
      plan12m: "1 Sanad (44% Dhimis)",
      planLifetime: "Weligaa",
      plan1mVip: "1 Bil VIP",
      plan3mVip: "3 Bilood VIP (15% Dhimis)",
      plan6mVip: "6 Bilood VIP (28% Dhimis)",
      plan12mVip: "1 Sanad VIP (44% Dhimis)",
      planLifetimeVip: "Weligaa VIP",
      periodMonthly: "bishiiba",
      periodQuarterly: "3 bilood",
      periodSemiAnnual: "6 bilood",
      periodYearly: "sanadkiiba",
      periodLifetime: "weligaa"
    },
    Community: {
      following: "Ku Raacsan Tahay",
      follow: "Raac",
      deletePost: "Tirtir Qoraalka",
      deepLinkShare: "La Wadaag"
    },
    Workshops: {
      topicLabel: "Mawduuca",
      timeSlotLabel: "Wakhtiga",
      topicPreMarriage: "Hanuuninta Ka Hor Guurka",
      topicFinance: "Qorsheynta Maaliyadda Qoyska",
      topicConflict: "Xallinta Khilaafka",
      topicGeneral: "La-talinta Guud"
    },
    Dashboard: {
      profile: {
        completion: "Dhamaystirka Profile-ka"
      }
    }
  },
  ar: {
    Subscription: {
      hub: "بيتسب Diamond و VIP",
      welcomeVip: "مرحباً بك في مرتبة VIP",
      welcomeDiamond: "مرحباً بك في مرتبة Diamond",
      descVip: "تحكم كامل في خصوصيتك، ميزات التخفي الكاملة، ومكانة التاج الذهبي لمطابقة النخبة.",
      descDiamond: "افتح تطابقات غير محدودة، تواصل مع الملفات مباشرة، استمتع بالدروس المتخصصة، وابحث عن شريكك مدى الحياة اليوم.",
      diamondPlans: "خطط Diamond",
      vipPlans: "خطط VIP",
      keyFeatures: "الميزات والمزايا الرئيسية",
      feat1Title: "تغذية غير محدودة للتطابق",
      feat1Desc: "تجاوز حدود بطاقات الثقة اليومية واستكشف الملفات الشخصية دون قيود.",
      feat2Title: "محادثة خاصة مباشرة",
      feat2Desc: "ابدأ الدردشة مع التطابقات فوراً دون حدود انتظار.",
      feat3Title: "عرض التفاصيل الكاملة والسير الذاتية",
      feat3Desc: "اكشف السمات المشوشة والأوصاف وسيرة المستخدم الكاملة.",
      feat4Title: "خدمة عملاء ذات أولوية",
      feat4Desc: "طلبات الدعم وتحديثات حالة التحقق لديك تحصل على الأولوية.",
      feat5Title: "مرتبة التاج الذهبي",
      feat5Desc: "تميّز بشارة تاج أنيقة على صورتك وصفحة تفاصيلك.",
      feat6Title: "وضع الشبح والخصوصية",
      feat6Desc: "طمس صورتك الرمزية بالكامل وإخفاء اسمك الكامل.",
      feat7Title: "ضوابط الإخفاء عبر الإنترنت",
      feat7Desc: "إخفاء مؤشرات نشاطك عبر الإنترنت وحالة الكتابة وإيصالات القراءة.",
      feat8Title: "جميع مزايا Diamond مشمولة",
      feat8Desc: "استمتع بوصول Diamond الكامل بالإضافة إلى ميزات VIP الحصرية.",
      selectedCategory: "الفئة المختارة",
      totalAmount: "إجمالي المبلغ المستحق",
      discountApplied: "تم تطبيق الخصم",
      completeUpgrade: "أكمل الترقية",
      secureGateway: "بوابة آمنة • يتم التفعيل فوراً",
      bestOffer: "أفضل عرض",
      submitClaimBtn: "دفعت ولم يتم التفعيل؟ قدّم مطالبة",
      claimTitle: "تقديم مطالبة بالدفع",
      claimTxLabel: "رقم المعاملة (Transaction ID)",
      claimTypeLabel: "نوع الدفع",
      claimExplainLabel: "الشرح",
      claimExplainPlaceholder: "اشرح ما حدث (المبلغ المدفوع، الطريقة، إلخ)...",
      claimSubmit: "تقديم المطالبة",
      paymentFailed: "فشل في تهيئة الدفع",
      claimSuccess: "تم تقديم المطالبة",
      claimSuccessMsg: "تم تسجيل مطالبتك بالدفع بنجاح تحت رقم التذكرة {ticket}. سيتحقق منها المسؤولون قريباً.",
      typeVip: "ترقية VIP",
      typeDiamond: "ترقية Diamond",
      typeCoins: "حزمة العملات (100-10000)",
      plan1m: "شهر واحد",
      plan3m: "3 أشهر (خصم 15%)",
      plan6m: "6 أشهر (خصم 28%)",
      plan12m: "سنة واحدة (خصم 44%)",
      planLifetime: "وصول مدى الحياة",
      plan1mVip: "شهر واحد VIP",
      plan3mVip: "3 أشهر VIP (خصم 15%)",
      plan6mVip: "6 أشهر VIP (خصم 28%)",
      plan12mVip: "سنة واحدة VIP (خصم 44%)",
      planLifetimeVip: "VIP مدى الحياة",
      periodMonthly: "شهرياً",
      periodQuarterly: "ربع سنوي",
      periodSemiAnnual: "نصف سنوي",
      periodYearly: "سنوياً",
      periodLifetime: "مدى الحياة"
    },
    Community: {
      following: "تتابعه",
      follow: "تابع",
      deletePost: "حذف المنشور",
      deepLinkShare: "مشاركة"
    },
    Workshops: {
      topicLabel: "الموضوع",
      timeSlotLabel: "الفترة الزمنية",
      topicPreMarriage: "إرشادات ما قبل الزواج",
      topicFinance: "التخطيط المالي للأسرة",
      topicConflict: "حل النزاعات",
      topicGeneral: "الاستشارة العامة"
    },
    Dashboard: {
      profile: {
        completion: "اكتمال الملف الشخصي"
      }
    }
  }
};

function deepMerge(target, source) {
  for (const key in source) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

for (const [lang, data] of Object.entries(subKeys)) {
  const filePath = `messages/${lang}.json`;
  const content = JSON.parse(require('fs').readFileSync(filePath, 'utf8'));
  deepMerge(content, data);
  require('fs').writeFileSync(filePath, JSON.stringify(content, null, 2), 'utf8');
  console.log(`Updated ${lang}.json with Subscription/Community/Workshops keys`);
}
